(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ConverterCore=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';

const aliases={date:['date','transaction date','posted date','posting date'],details:['description','descriptif','details','transaction','merchant','name','memo','payee'],out:['withdrawal','withdrawals','retrait','debit','debits','money out','amount out','charge'],in:['deposit','deposits','depot','credit','credits','money in','amount in'],amount:['amount','transaction amount','value']};

function norm(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function cleanNum(value){let text=String(value??'').trim();if(!text)return null;const par=/^\(.*\)$/.test(text);text=text.replace(/[\s\u00a0$]/g,'').replace(/[^0-9.,-]/g,'');if(text.includes(',')&&!text.includes('.'))text=text.replace(',','.');else if(text.includes(',')&&text.includes('.')){if(text.lastIndexOf(',')>text.lastIndexOf('.'))text=text.replace(/\./g,'').replace(',','.');else text=text.replace(/,/g,'')}const number=Number(text);if(!Number.isFinite(number))return null;return par?-Math.abs(number):number}
function looksLikeDate(value){return /^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(String(value||'').trim())||/^\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}$/.test(String(value||'').trim())}
function formatDate(value){value=String(value??'').trim();if(!value)return'';let date;const french=norm(value).match(/^(\d{1,2})\s+([a-z]+)\s+(\d{4})$/);if(french){const months={jan:0,janv:0,fev:1,fevr:1,mar:2,mars:2,avr:3,avril:3,mai:4,jun:5,juin:5,jul:6,juil:6,aou:7,aout:7,sep:8,sept:8,oct:9,nov:10,dec:11},month=months[french[2]];if(month!==undefined)date=new Date(Number(french[3]),month,Number(french[1]))}if(!date){if(/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(value)){const [year,month,day]=value.split(/[\/-]/).map(Number);date=new Date(year,month-1,day)}else date=new Date(value)}if(isNaN(date))return'';return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function parseLine(line,delimiter){let output=[],current='',quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'){if(quoted&&line[i+1]==='"'){current+='"';i++}else quoted=!quoted}else if(char===delimiter&&!quoted){output.push(current);current=''}else current+=char}output.push(current);return output}
function delimiter(text){const first=text.split(/\r?\n/).find(line=>line.trim())||'';return ['\t',',',';'].sort((a,b)=>parseLine(first,b).length-parseLine(first,a).length)[0]}
function isTdHeaderless(matrix){if(!matrix.length||matrix[0].length!==5||!looksLikeDate(matrix[0][0]))return false;return matrix.slice(0,Math.min(8,matrix.length)).every(row=>row.length===5&&looksLikeDate(row[0])&&String(row[1]||'').trim()&&((cleanNum(row[2])!==null)!==(cleanNum(row[3])!==null))&&cleanNum(row[4])!==null)}
function isDesjardinsHeaderless(matrix){if(!matrix.length||matrix[0].length!==14||!looksLikeDate(matrix[0][3]))return false;return matrix.slice(0,Math.min(8,matrix.length)).every(row=>row.length===14&&looksLikeDate(row[3])&&String(row[5]||'').trim()&&((cleanNum(row[7])!==null)!==(cleanNum(row[8])!==null))&&cleanNum(row[13])!==null)}
function parseSourceText(text,name){text=String(text||'').replace(/^\uFEFF/,'').trim();if(!text)return null;const separator=delimiter(text),lines=text.split(/\r?\n/).filter(line=>line.trim()),matrix=lines.map(line=>parseLine(line,separator));let headers,rows,format='headered';if(isTdHeaderless(matrix)){headers=['Date','Description','Withdrawals','Deposits','Balance'];rows=matrix;format='td-headerless'}else if(isDesjardinsHeaderless(matrix)){headers=['Institution','Account','Code','Date','Sequence','Description','Unused','Withdrawals','Deposits','Unused 2','Unused 3','Unused 4','Unused 5','Balance'];rows=matrix;format='desjardins-headerless'}else{headers=matrix.shift().map((header,index)=>header.trim()||`Column ${index+1}`);rows=matrix}return{headers,rows:rows.map(row=>headers.map((_,index)=>row[index]??'')),name,format}}
function findHeader(headers,names){let index=headers.findIndex(header=>names.some(alias=>norm(header)===norm(alias)));if(index<0)index=headers.findIndex(header=>names.some(alias=>norm(header).includes(norm(alias))));return index}
function cleanMerchant(value){let text=String(value||'').trim().replace(/\s+/g,' ');for(const city of ['SAINT-LAURENT','GATINEAU','NEPEAN','OTTAWA','HULL','TORONTO','MONTREAL','VANCOUVER','EDMONTON']){const pattern=new RegExp(`\\s+${city.replace('-','\\-')}(?:\\s+(?:QC|ON|Q|O))?$`,'i');if(pattern.test(text)){text=text.replace(pattern,'').trim();break}}return text}

function canonicalTransaction({date='',rawDescription='',amountSigned=0,direction='',sourceProfile='',sourceFile='',sourceRow=0,warnings=[],metadata={}}){return{date,rawDescription,normalizedDescription:rawDescription,amountSigned,direction,sourceProfile,sourceFile,sourceRow,status:warnings.length?'review':'ready',warnings:[...warnings],metadata:{...metadata}}}
function classifyIssue(message){const text=String(message||'');if(/not recognized|Could not identify/.test(text))return{kind:'no-output',label:'No usable output',message:text};if(/date could not be read|negative amount|Possible duplicate/.test(text))return{kind:'review',label:'Review recommended',message:text};return{kind:'skipped',label:'Row skipped',message:text}}
function findingsFor(issues){return issues.map(classifyIssue)}
function adaptTransaction(transaction,destination){const amount=Math.abs(Number(transaction.amountSigned));if(destination==='savings')return{date:transaction.date,details:transaction.normalizedDescription,amount,type:transaction.direction,selected:true,canonical:transaction};return{date:transaction.date,details:transaction.normalizedDescription,amount,type:transaction.direction,selected:true,canonical:transaction}}

function recognizeStandard(destination,source){const headers=source.headers,date=findHeader(headers,aliases.date),details=findHeader(headers,aliases.details),out=findHeader(headers,aliases.out),incoming=findHeader(headers,aliases.in),amount=findHeader(headers,aliases.amount);if(destination==='savings'){if(source.format==='td-headerless'&&date>=0&&details>=0&&out>=0&&incoming>=0)return{kind:'split',profile:'td-savings-headerless',label:'TD Savings · headerless 5-column export',date,details,out,in:incoming};if(date>=0&&details>=0&&out>=0&&incoming>=0)return{kind:'split',profile:'desjardins-savings-french',label:'Desjardins Savings · pasted French statement',date,details,out,in:incoming};const name=findHeader(headers,['name']);if(date<0||name<0||amount<0)return null;return{kind:'signed',profile:'tangerine-isa',label:'Tangerine ISA · signed amount export',date,details:name,amount}}
  if(date<0||details<0)return null;if(out>=0&&incoming>=0){let label='Separate money-out and money-in columns',profile='generic-split';if(source.format==='td-headerless'){label='TD account activity · headerless 5-column export';profile='td-account-headerless'}if(source.format==='desjardins-headerless'){label='Desjardins chequing · headerless 14-column export';profile='desjardins-chequing-headerless'}return{kind:'split',profile,label,date,details,out,in:incoming}}if(amount>=0)return{kind:'signed',profile:'generic-signed',label:'Single signed amount column',date,details,amount};if(out>=0)return{kind:'out',profile:'generic-money-out',label:'Money-out column only',date,details,out};if(incoming>=0)return{kind:'in',profile:'generic-money-in',label:'Money-in column only',date,details,in:incoming};return null}

function convertStandard(destination,source){const detected=recognizeStandard(destination,source),issues=[],transactions=[];if(!detected){issues.push(destination==='savings'?'This Savings source is not recognized. Supported profiles currently include Tangerine ISA, TD account activity, and Desjardins pasted statements.':findHeader(source.headers,aliases.date)<0||findHeader(source.headers,aliases.details)<0?'Could not identify the Date and Details/Description columns.':'Could not identify an Amount, Debit/Withdrawal, or Credit/Deposit column.');return{detected:null,issues,findings:findingsFor(issues),transactions,rows:[],excluded:0}}
  source.rows.forEach((row,index)=>{const date=formatDate(row[detected.date]),description=String(row[detected.details]||'').trim(),warnings=[];let raw='',direction='';if(detected.kind==='split'){const outgoing=cleanNum(row[detected.out]),incoming=cleanNum(row[detected.in]);if(outgoing!==null&&incoming!==null){issues.push(`Row ${index+1}: both money-out and money-in columns contain an amount.`);return}if(outgoing!==null){raw=outgoing;direction='Money Out'}else if(incoming!==null){raw=incoming;direction='Money In'}}else if(detected.kind==='signed'){const amount=cleanNum(row[detected.amount]);if(amount!==null){raw=amount;direction=amount<0?'Money Out':'Money In'}}else if(detected.kind==='out'){raw=cleanNum(row[detected.out]);direction='Money Out'}else{raw=cleanNum(row[detected.in]);direction='Money In'}if(raw===null||raw===''){issues.push(`Row ${index+1}: no usable amount found.`);return}if(!date){const warning=`Row ${index+1}: date could not be read.`;issues.push(warning);warnings.push(warning)}transactions.push(canonicalTransaction({date,rawDescription:description,amountSigned:direction==='Money Out'?-Math.abs(Number(raw)):Math.abs(Number(raw)),direction,sourceProfile:detected.profile,sourceFile:source.name,sourceRow:index+1,warnings}))});return{detected,issues,findings:findingsFor(issues),transactions,rows:transactions.map(transaction=>adaptTransaction(transaction,destination)),excluded:0}}

function recognizeExpenseProfile(source){const headers=source.headers.map(norm),has=value=>headers.includes(norm(value));if(has('Transaction date')&&has('Transaction')&&has('Name')&&has('Amount'))return{id:'tangerine-world-mc',label:'Tangerine World MasterCard'};return null}
function convertExpense(source){const profile=recognizeExpenseProfile(source),issues=[],transactions=[],excludedByMonth={};if(!profile){issues.push('This Expense Calculator source is not recognized. The current profile expects Transaction date, Transaction, Name and Amount columns.');return{detected:null,issues,findings:findingsFor(issues),transactions,rows:[],months:[],excludedByMonth}}
  const dateIndex=findHeader(source.headers,aliases.date),nameIndex=findHeader(source.headers,['name']),amountIndex=findHeader(source.headers,aliases.amount),detected={kind:'expense',profile:profile.id,label:`${profile.label} · expense export`,date:dateIndex,details:nameIndex,amount:amountIndex};source.rows.forEach((row,index)=>{const amount=cleanNum(row[amountIndex]),date=formatDate(row[dateIndex]),month=date.slice(0,7);if(amount===null){issues.push(`Row ${index+1}: amount could not be read.`);return}if(amount>=0){if(month)excludedByMonth[month]=(excludedByMonth[month]||0)+1;return}const rawDescription=String(row[nameIndex]||'').trim(),warnings=[];if(!date){const warning=`Row ${index+1}: date could not be read.`;issues.push(warning);warnings.push(warning)}const transaction=canonicalTransaction({date,rawDescription,amountSigned:amount,direction:'Money Out',sourceProfile:profile.id,sourceFile:source.name,sourceRow:index+1,warnings,metadata:{month,transactionType:'Expense'}});transaction.normalizedDescription=`Tangerine MC (${cleanMerchant(rawDescription)})`;transactions.push(transaction)});transactions.reverse();return{detected,issues,findings:findingsFor(issues),transactions,rows:transactions.map(transaction=>({...adaptTransaction(transaction,'expense'),month:transaction.metadata.month,original:transaction.rawDescription,order:transaction.sourceRow-1})),months:[...new Set(transactions.map(transaction=>transaction.metadata.month).filter(Boolean))].sort(),excludedByMonth}}

function parseSharedBlock(text,payer,kind,block,issues){const transactions=[];String(text||'').split(/\r?\n/).forEach((raw,index)=>{const line=raw.trim().replace(/^\|\s*/,'').replace(/\s*\|$/,'');if(!line||/^[-|:\s]+$/.test(line))return;const match=kind==='spreadsheet'?line.match(/^\$?\s*(-?[\d,]+(?:\.\d+)?)\s+(.*)$/):line.match(/^(.*?)\s+\$?\s*(-?[\d,]+(?:\.\d+)?)$/);if(!match){issues.push(`Block ${block}, line ${index+1}: expected ${kind==='spreadsheet'?'amount followed by description':'description followed by amount'}.`);return}const amount=cleanNum(kind==='spreadsheet'?match[1]:match[2]),description=String(kind==='spreadsheet'?match[2]:match[1]).trim(),warnings=[];if(amount===null||!description){issues.push(`Block ${block}, line ${index+1}: amount or description could not be read.`);return}if(amount<0){const warning=`Block ${block}, line ${index+1}: negative amount ${amount.toFixed(2)} needs review.`;issues.push(warning);warnings.push(warning)}transactions.push(canonicalTransaction({rawDescription:description,amountSigned:amount,direction:'Money Out',sourceProfile:kind==='spreadsheet'?'shared-spreadsheet':'shared-message',sourceFile:`Shared block ${block}`,sourceRow:index+1,warnings,metadata:{block,payer:String(payer||'').trim()}}))});return transactions}
function buildSharedConversion(blocks){const issues=[],transactions=[...parseSharedBlock(blocks[0].text,blocks[0].payer,'spreadsheet',1,issues),...parseSharedBlock(blocks[1].text,blocks[1].payer,'message',2,issues)],counts=new Map();transactions.forEach(transaction=>{const key=`${transaction.amountSigned.toFixed(2)}|${norm(transaction.normalizedDescription)}`;transaction.metadata.duplicateKey=key;counts.set(key,(counts.get(key)||0)+1)});const duplicateKeys=[...counts].filter(([,count])=>count>1),possibleDuplicates=duplicateKeys.reduce((sum,[,count])=>sum+count,0);transactions.forEach(transaction=>transaction.metadata.duplicate=counts.get(transaction.metadata.duplicateKey)>1);duplicateKeys.forEach(([,count],index)=>issues.push(`Possible duplicate group ${index+1}: ${count} matching rows retained for review.`));const rows=transactions.map(transaction=>({date:'',payer:transaction.metadata.payer,amount:transaction.amountSigned,details:transaction.normalizedDescription,type:'Shared Expense',selected:true,block:transaction.metadata.block,line:transaction.sourceRow,duplicateKey:transaction.metadata.duplicateKey,duplicate:transaction.metadata.duplicate,canonical:transaction}));return{rows,transactions,issues,findings:findingsFor(issues),possibleDuplicates}}
function convertParsedSource(destination,source){return destination==='expense'?convertExpense(source):convertStandard(destination,source)}

return{norm,cleanNum,looksLikeDate,formatDate,parseSourceText,cleanMerchant,canonicalTransaction,classifyIssue,findingsFor,adaptTransaction,recognizeStandard,recognizeExpenseProfile,convertStandard,convertExpense,buildSharedConversion,convertParsedSource};
});
